### PR TITLE
Add sqrt function

### PR DESCRIPTION
**Pull request by GlitchlessCode**
# The Suggestion
Add a square root function (√x) to the set of functions
# Implementation description
- Uses a recursive method to approximate the square root of macro $(x)
- This implementation is fast, reads and writes as little as I could implement, and is precise to several decimal points.
- Ensured same formatting and error checking to the original codebase
- Updated README to add `gm:sqrt` to list of functions

### CODE REVIEW

**Comment by gibbsly** [comment]
woah, impressive thanks! I gave up on trying to implement this

**Comment by GlitchlessCode** [comment]
By the way, I ran some test data:
## $(x) missing
fail (Correct)

## $(x) < 0
fail (Correct)

## typeof $(x) !== number
fail (Correct)

## $(x) == 0
~0.0f (Correct)
(This one was very slightly bigger than 0, but only after a lot zeros. It's effectively equivalent to 0)

## $(x) == 0.25f
~0.5f (Correct)

## $(x) == 1.0f
~1.0f (Correct)

## $(x) == 2.0f
~1.4142135f (Correct)
aka
~√2 (Correct)

## $(x) == 64.0f
8.0f (Correct)

**Comment by GlitchlessCode** [comment]
> woah, impressive thanks! I gave up on trying to implement this

Ha, thanks. It's not my own algorithm, it's just one of the more common ones out there, but I just figured out how to implement it in MC, that's all

**Comment by gibbsly** [comment]
still more than I could figure out, I was mostly unmotivated because I only needed it to calculate distance and that has its own operation

**Comment by GlitchlessCode** [comment]
> still more than I could figure out, I was mostly unmotivated because I only needed it to calculate distance and that has its own operation

Fair. I'm personally planning to implement arcsin, arccos and arctan, which is why I wanted the sqrt, cause I couldn't find a simple solution for the inverse trigs that didn't use sqrt, or vice versa.

Which is why we have to settle for an approximation, but it's still very accurate at least.

**Comment by gibbsly** [comment]
I see, I think you have more ambitions for this repo than I do, I just did the operations I need accurate outputs for, I'll absolutely merge any ops you add though

**Pull request merged**
